name: CMake compiler build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/setup-nasm@v1

    - name: Configure CMake
      run: cmake -S . -B ./build

    - name: Build
      run: cmake --build build/ -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --test-dir .

